---
language: minimal

services:
- docker

env:
  global:
  # Docker credentials
  # - DOCKER_USERNAME
  # - DOCKER_PASSWORD
  - secure: "q5zjG6nNEUNWICPvcWclz4nnzugK5ug9qlpduiJ22GTrU+oP9zJwBzBfN6Jgoj4VFvlCA9ARyLyq1yrWckxziHRjPqYWn5IXLWIXMdyLteeMNOyHwLtpTpXpch+VyFZi/qvmkkziGbDQ7Uq9pvYgl+WdTKdY83kh4r+8OecZ2sZleamtmg7n1HbJs3gTFpWki34PkTbZ/sv89zb02ce9P0FML5ZH+rBplvPoB6/7aziX3PNi0NfIj50VC9aVBqayra40uJn3KnjXFLUbILqOZsoFeSY0wHERF27UcM7UKciG6O6DfMH/2ta2d/bcSLBnWxFb+7mf1yEFLJkL2n4JA/2IQCnVhDiAgQYc6UT6RNQUxZeD2SCqBordZYDZAN4LoVmXz4luyYqEv/DI/3lh9xJwp6xrAFqZcfkDw6M8b1G1O0I/SbYxXI47ebrix2IIJWhCPDkxDJk7sagOUfg4NKowJwlRxgLSQrg5MdxvZf3RDax5X9YeFDMtzmk57fzp4f+udtZp7Qp5R+s78DRfEQTDtC2cEiX6MhndRic4URrq97TWzhVbuqSLlPhzczyO2odpyI+ZLcEQB+ZDm3tz4F/AAwlUvg4rHgvdcLF8P4DNmWO2YdLvhmeMw9uNT6ZJZLkqKkxlPTORaDht1nGpwzQXl1PHDWZ/HKuTR7VJHos="
  - secure: "RQ2yy9gA7YXTPNwVjgOvRCYrtJxzRQHS/FR+Z37zA6RfCWL5ZC5IVAhvjbUBsnQ6hS3+p94/of5AnLdA8/0lsMR/1vV1jq431IassRBlnr9kVA0PjcZHNAgkY4vt2WQsTSKKQB7QF7vB+A6haRKOSqUYoT7cagUh9hqakEzCNVPweYS3vfnZ+aawB15xaAn8mXYRfSAAx59srf3YG/TN29kShqnht3HLyV3j7eErEpWhg9ZbGzHvY4ehe+4rDHLFm4qv2mzjTi1qnnJlQZ1Y++dZe2U8iPHatoz1+uirfRodAMTZGTqcWpfBkDCICpV+v6MjldMwntG5rhB/5hp4pxJdYPTcAJoBAafY3TMnDIbArCWLhQ1vvG02iDTZCSBJITVWUm5tYUgnBkAiuevVgbtFbP/45NIYlmVq2hHxPxH2VOV114CXbU4s8Y0EnG4bZV+NoEZjosQzWHmASnemM2w3TlZX8lc946nLlhoTsJxnzRfAKkX0YngwzGgkOlpvRh2ISgMSm4SYD2wNAbOqsP95Ve2WlVGXoODeOUTOhb/bXShauiTuJ8Q4QnAyCSAi4qn6kQ+3H13ql6NATTgrT4xe+fOLBXTjFmt1c0P8rJrnk4LucmWRbBWmK8xdb9Kd1drlwDAcdzFP8pQX3WCZHDAYVfKXXF8QtEsFj7W2pq4="

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io

script:
- docker build -t alanbchristie/operator-pysimple -f build/Dockerfile .
- docker push alanbchristie/operator-pysimple
