---
language: python

services:
- docker

env:
  global:
  - secure: "KxbNxBHuUL51aRLzHo03iJo+ab+AZxYAIl6MIOpQnKBeyJiI9K8kgsI4SF4d4bXyoL6C2nwB1yDLGJLnH9vXBR9scfM3YoB5sZovDCqzwHlYA+xrOxezROqljCY5XKZ2m+8mZ27n63XCXNHOPP6OEkZNh2TEMR/Pv+YDHxFpVOh9NAEDSGqLhbRGPA537kQux2TWAvmVVzryQ3yif0EY0G0U3Z+c8O5/qAmLi3vlJHHF2qKgEMhToxhNxjTtEOLY6E7l1Hnu0AaZksyHLAt4eV5A0h4G0eO5F3rugq7K+//vOF1ZIHQyMkYUxjo4BjOdSkqzIaZ3O1hViW3fhJ9Pq/9+RczhX4agfhZYYj4kTxm/7Wjk6MeFyxRubyILZ1HTKXuWnZ+zxTJEeV+8Hs+HPbLUOZYF7VvoGnZKbRfa/DnvptVKbknGHyWLrU/LpAN7FjNKKbIhQlaH2t+izzbcbjPTgMgmDIvYv5fwaqdOJG6louJES4CdaXkIUwvWwBa8k7u/Xinnphnk+dE9yJpiJf9rbzXQvc4rTBMrqucpCuDUqCoS8brqhG2OXgmClUgAE2dtSiY0rsvbKil7Os8GQm1VmMWsMj/Ic0bSoJW5HOSfv1vzCc4Ket6TFjxrHnsUM8MQ8E2Pm956CO1AKpM9eBQj4uQSR9wNfCBnBYJujb8="
  - secure: "jm9M7QtzD8kQLGM0WBZgEGjH0/lqWn04LYFL/6scNsuyPqF7vnIiE/olONsiIH+5mag8RhYwdjN6hrm62FWZebpQ4TytwEkN6G8TOqp0ZRmfUjU2nRWOcdKy5ERPzYSx2jTSz3RRjaunrn1v0kADgKC29FJONdjgaEcYU4fyRrzAPEUBm2J/kr3wi55vFc8cihrY+jjGGh2j1/aRggXbgm28wj+7md1R7184nW8DlYU/P7TR8V8KTwzxKNxC+2CCKM7JOrjd8JQz/F20bL+77hPN6kaLIcw0BuhyqrOER6KURkQ/F356fs2YNrJvL0dsDQNR4XMbVpwUOdViKxBYRUMcdT7WviSUiLymKlJ+ac0XlfDkFqjYPG4hSIu6Gh+vZW6fX1bNeeQ/P/xczOc6p4VjJgjXCxYag18J6JBxq+HM0qoERtkn8MsO6C+l3/9ZKZP+CzpojO42UoUIIkHMCJ2WuQqsFwe4/jjCPPWs0dNYwDW7J6mmnXAItOWtxZ3SNv1UQy7etZKENk79VmJdMHsZT0A74bM1lP9wLnSBtSQhpkPItStaYr6Pcu0RRhNYF+SXo7HlGiBI75nKQcGDld0b1NYvetYYxWdyDor2dwZxSU5CF/yQcPIW5nYJhXlV/6oxo92yAfOaZfdFq+2POdQ232jnq7IuOVTyj6uVww0="

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- docker build -t alanbchristie/operator-pysimple -f build/Dockerfile .
- docker push alanbchristie/operator-pysimple
