---
language: python

services:
- docker

env:
  global:
  - secure: "VO40V2vi2zxSd5gdu8wFLBU6sQeV650Z5IfE6YmR8uRW7H5HUkm5r6RWE+iFh7x/PiEGF+cxJl8172nFGoMp7fBCfjDdQBVd2cAvCHpY3ajBfibQmcgXd1SxiEVWN7X26HRv1xS/AaeZxAVO4Pj6V7AxjsplomsCebOo07CHTdImaEESbnk3XASmYzbaCTsQkki/57Jf/madwnEi1FOQIYKpR1loDPv+mLAo2nNN/l7m0ueqmg5w5upEHdO6TWdgCLql45k33W3KAQ4+VViDh22OZ9c84ZL+lEwalS7gP3siQwuaM8qdEOM+Q/5MIB6ggOKrSilH5iohQt8l3aZG35FcLRETfQuWBdix6Vo+1Fwy7gTdnxEEOdaITrRHrLSGlhFrb2n0mqc0KxD3l3r14mD9udIO3mcF4QhKdjScaPrelqYiDsfGWnA2RHd1PEc7+np4vlb9odF3UfTwA4pljeXOMg0x42LnfoMvmtk56RHkT2FA/+R+3G39mlS3MKjcFdtDchMVumieOL67+mJ2SHgqukUpo8R7vhgkqwxnUWsDVERz3/xqfDQvIQHsqMU57AJwTKQbPKA67pndcXKCABUhjnevU5uTk0Ei6M8PutsTlrLY6QqUnAfQGeTCpEzDKpzlZHWdynBOJA1PiCntpZvo0Hn2fkeGLDLLNiHhdg8="
  - secure: "eq7yNFhLfiozOcrC4XC5RAUWoUIiIvlVLh0Ou+jdP6HV7p1EMHEIX5N2Pw/8AmG7dJ2z7ceLJ0CnWtX+DqqSjP0sy28SxLp6n38H2rk/IUiSnR0AbEdx+70bfzO0pnLRccbQtHxHNmvC8WqGXvkX0ClwhdhN6j2pq4CtEAdokzdjCu07dGXbqxf0K27CeUWRGuR4TFthnLEy6RfUS7tUCNf84XHnolfcapvJeT5Y/jrYNvbSr8hxe3+8WoYlB2bxqZ77Lb1dvUlaD/ePSTF3aRGbet7yZaXksRD5C1kTOBgLqEXONIJD3cSnYNdWgptw30N9ekgeey5kxKvJk6mutE0zd1o9+DOiSPbxhH9Hq+RTWU1El/B2QalLFIddMtvNCOI6z9US01Sh+djcWbJm9yhc8za4QBmF3bTmLe+1HHvdp3Bq7IZq0e61+P1BNPKW4vdpiiiMTIUti0Q80hq+EZ67X1f06mrJIApPXN94zjvCQSbtzcuI7DT8Sr9+lcdzFwro8SgoWe0cVmHr0ierHQcZjbISRa0o8kDYBeWORZ5ng1nlp/yUeeNEANBUdOu+5HSF5IXinYNcRVLJiRtQOl4Rjd4UzqpXyVAtfVRrxlMoTkJeDo0aqpg4ggANlm/LpUxhuuAN45knF+KL+gH4yauCj5o5CM9jEFqsCHVVSnQ="

before_script:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
- docker build -t alanbchristie/operator-pysimple -f build/Dockerfile .
- docker push alanbchristie/operator-pysimple
