---
language: python

services:
- docker

env:
  global:
  - secure: "KxbNxBHuUL51aRLzHo03iJo+ab+AZxYAIl6MIOpQnKBeyJiI9K8kgsI4SF4d4bXyoL6C2nwB1yDLGJLnH9vXBR9scfM3YoB5sZovDCqzwHlYA+xrOxezROqljCY5XKZ2m+8mZ27n63XCXNHOPP6OEkZNh2TEMR/Pv+YDHxFpVOh9NAEDSGqLhbRGPA537kQux2TWAvmVVzryQ3yif0EY0G0U3Z+c8O5/qAmLi3vlJHHF2qKgEMhToxhNxjTtEOLY6E7l1Hnu0AaZksyHLAt4eV5A0h4G0eO5F3rugq7K+//vOF1ZIHQyMkYUxjo4BjOdSkqzIaZ3O1hViW3fhJ9Pq/9+RczhX4agfhZYYj4kTxm/7Wjk6MeFyxRubyILZ1HTKXuWnZ+zxTJEeV+8Hs+HPbLUOZYF7VvoGnZKbRfa/DnvptVKbknGHyWLrU/LpAN7FjNKKbIhQlaH2t+izzbcbjPTgMgmDIvYv5fwaqdOJG6louJES4CdaXkIUwvWwBa8k7u/Xinnphnk+dE9yJpiJf9rbzXQvc4rTBMrqucpCuDUqCoS8brqhG2OXgmClUgAE2dtSiY0rsvbKil7Os8GQm1VmMWsMj/Ic0bSoJW5HOSfv1vzCc4Ket6TFjxrHnsUM8MQ8E2Pm956CO1AKpM9eBQj4uQSR9wNfCBnBYJujb8="
  - secure: "UtlunzquYuqlBoeFYzNxI7qWmX+suXIzLkr6fHyNuGoMc6kn+gxl7zlzvilKBfQ/aDnoDikJOwPif0v30zYhGjbBuqiTDWxqL6YmaurPjDPa5FwAPEmAdH/NNNfKc5lRsKmSHXWpaO/Tt6jklcLQzCLmY5EvAiFAcyn3fm1bEDJbAU3komIdnDN2gcFb8gJLHbQPjMFYvJGK0B0W7vBCeGJTYr9RxVJSxZFp8VN++W8yOT0COIzt8QeJeMGfY28kBItpxbyusGwWUPWD6PQUMoYYySVVi0CiqJDY8m9L0OvTKdu/K4Eqy9/sR7mUYH5KJzFVlrpkfF231h8hVPZbkLCX3ZJrkLXCibOdoKu7ujUV1igD7zlnTrVsvOVm0l0+vWxOsCgM/SGQZNC65+alqyn9kAnCfn3yTMLUgD01MUbaMHBho888DISEb1/PS1H9AV1elBX+qSSdeWtI6VvgsfwOKO2gyR6vzu6UyPhRc/EtmlTtWimaCrV3wLCEVk4x+/FkmHLUwHo5XelVNDn7zZMzpDt3nzNl2XOKCxEWx2nwKZ8d8DR/TcakPjavLfsS4vLFB7MkpAKBMp9+GFgREn1Kq2mOJhO4/z21RDRJ/he0eZEDoqdIeLkcqQCrKF65Ij82xwAuGAU0pnQXxuvzdX7VdMfuQwM8Wa91kqyVnac="

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- docker build -t alanbchristie/operator-pysimple -f build/Dockerfile .
- docker push alanbchristie/operator-pysimple
