---

# -----------------
# Control variables (Travis Settings)
# -----------------
#
# You must set the following: -
#
# DOCKER_USERNAME
# DOCKER_PASSWORD

language: minimal

services:
- docker

env:
  global:
  - DOCKER_IMAGE=operator-pysimple

stages:
  # Build stage
  # Executed on branches other than master
  # and where no tag has been defined
- name: build
  if: tag IS NOT present AND branch != master
  # Publish stage
  # Executed on master or when a tag has been defined
- name: publish
  if: tag IS present OR branch == master

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io

matrix:
  include:
  - stage: build
    script:
    - docker build -t "$DOCKER_USERNAME"/"$DOCKER_IMAGE" -f build/Dockerfile .
  - stage: publish
    name: Publish latest
    script:
    - docker build -t "$DOCKER_USERNAME"/"$DOCKER_IMAGE":latest -f build/Dockerfile .
    - docker push "$DOCKER_USERNAME"/"$DOCKER_IMAGE":latest
    if: tag IS NOT present
  - stage: publish
    name: Publish tag
    script:
    - docker build -t "$DOCKER_USERNAME"/"$DOCKER_IMAGE":"$TRAVIS_TAG" -f build/Dockerfile .
    - docker push "$DOCKER_USERNAME"/"$DOCKER_IMAGE":"$TRAVIS_TAG"
    if: tag IS present
