---
language: minimal

services:
- docker

env:
  global:
  - secure: "dTKYrT6h0JPVHWUnrvBets6NPS4tkkQLyljz5QOdLF/l4AbFWWjHZjZ09ItpZFkd1k7oCAMnXSrRLW6pcgv7KolNSKrP5rOvLmlqx7x0/L978Iwpi+GBhoGes0SNPD3uD6XDzwjGeVvSJTZ9t+nokbA3tqxyFNh4Sj0sM+w6/rLLvB7QCgPtV8XGzbr+DFNJCdMOuuZYauNZc8Eh9tfTQ2+V9OppW4Iuc3J37viNrBa9YjVXuevhbbg0lmWiGzz/MYH6XFgSTKX+SC9Gfdqd6rxUU0Sk4M6iPsDCy99B7lkXf1bpuEwavN+lPaqGdMr4G/bVOti5Vi8x/9H31MBwwFome2jMoIVL6DJjjGrzDu91hRslIMmaLGRdr9KyOEwxflJqBIna1suatMPLiAZfM6HLQ1uVS22SgurXmawh8J0WUDUSezf84SyDmCQYsbU6/H79OSN9WSHOVl9jxKVFEIBUXs1p90Kd0WJe/b/znLcUhksh5Y1A+3bAiviXUxCisVsqqPUyvZl8c7PQkEZlNml/Zck+7mrMDrulZ3HjIx38K7ZUAPi4tPam0g2dyjM7468QjigNlNKtC0emHUkEaqR+XArYqV2rz130bHCySEgkk/j2GeE9Z5wUgaApJ1R7CxWgweROYIuRVr4yRm73SZZrE9S97kKLimKqgifJ1eA="
  - secure: "d1pbIcEOfB3tV23xBqOlTSSD39+6O+hpfv29Dfc5oOYM4Bsf0iQFl46rK1bhNjUxnKOMGv69X3FziAEYDtyK6zCzRfVfwecrU0dwNgowgj2DfJvwX6cA+KOD2kKeQra3fn5MgXy3yhsXsvo4yFiLnLhOej5aHSl0V2bae1iKymbbBByjRRMbYXzukMMxCVeQtCRqQ5CdN22wTChnzbyZpVEeiGt4qKZqpxe0jlqpSdlSqaecEeoY8UxBs++NrkEip1zRzOkLzji91wJk3kfsCKn5X283K4bZzWP/oRsQ9p5YQMgYawm5F5q3w57CSkZy13MaL3hXxQO44DK6wDNAdNMSDnncW/Uv35UlaTxweI1jli8c5whx6eC2L1p7qVVBTBjG3Cy5krJK9HHTidFrsKLCJFPt/MSFu5A83SGcwTxP+hOM5GKegRinXU875eW5xq1XmLxwuhgA5DNBSfuDwdX4FxGyiDQoEAbdWgnzCThSBI/Tjg59rzSUXrRJa7L9os4vXwqeTpQY61ee+WI6gi+Ip0V+NAsynzTzB2PyHb/43T4XZUus//oaWaacENlzFyrkpC7Onmi/Y8nytSAKsiezQhmMRaAygb7W+vrqLLlMV2uWQyqqOVzFv1Wai3Q/l/y0VuTBG6IZoewHL8JCXWTb+wc83GujoEUdPGlJJzs="

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io

script:
- docker build -t alanbchristie/operator-pysimple -f build/Dockerfile .
- docker push alanbchristie/operator-pysimple
