---
language: python

services:
- docker

env:
  global:
  - secure: "KxbNxBHuUL51aRLzHo03iJo+ab+AZxYAIl6MIOpQnKBeyJiI9K8kgsI4SF4d4bXyoL6C2nwB1yDLGJLnH9vXBR9scfM3YoB5sZovDCqzwHlYA+xrOxezROqljCY5XKZ2m+8mZ27n63XCXNHOPP6OEkZNh2TEMR/Pv+YDHxFpVOh9NAEDSGqLhbRGPA537kQux2TWAvmVVzryQ3yif0EY0G0U3Z+c8O5/qAmLi3vlJHHF2qKgEMhToxhNxjTtEOLY6E7l1Hnu0AaZksyHLAt4eV5A0h4G0eO5F3rugq7K+//vOF1ZIHQyMkYUxjo4BjOdSkqzIaZ3O1hViW3fhJ9Pq/9+RczhX4agfhZYYj4kTxm/7Wjk6MeFyxRubyILZ1HTKXuWnZ+zxTJEeV+8Hs+HPbLUOZYF7VvoGnZKbRfa/DnvptVKbknGHyWLrU/LpAN7FjNKKbIhQlaH2t+izzbcbjPTgMgmDIvYv5fwaqdOJG6louJES4CdaXkIUwvWwBa8k7u/Xinnphnk+dE9yJpiJf9rbzXQvc4rTBMrqucpCuDUqCoS8brqhG2OXgmClUgAE2dtSiY0rsvbKil7Os8GQm1VmMWsMj/Ic0bSoJW5HOSfv1vzCc4Ket6TFjxrHnsUM8MQ8E2Pm956CO1AKpM9eBQj4uQSR9wNfCBnBYJujb8="
  - secure: "k+cOcE3xrtrQePPMvLhUWYqfyZW1Tox7VGXwP5i+16qkIVb0l1uzGmHHXF3WmR+rhyPiMOyiR8Z7LuItYub7ZnV1DJ+6IikxKk+Pd9u9KEWsAbVQLLuGxBvjynSmsBBNDqs8Gy/4eL5KzBtLCUT/wQNzMp6dr1LyshTc6w9qYf/kdIDaAXc4FGsr+Uf8n9NJWizDW6bq6ZeMWiVZbzlM/7dC64kiTVOqoDmzNO0xZxrhhBScrZpT4WvjmaU3m1O2z+l+fFY2x4uERMeim38PpBcYMXgsXu0rDWxjR+AVVbQZf9JQeHCv6GCMrmAUEQ+G//VtQiMe0xIG0Kk3PFn+ZoArcBefc+prSM7XgqeiIorFreoO0CXpd+tcwkmXI7NCBlL1fLPlGTYlZ2WZsPsRiB7bGZRJwPuR/WOExBkmt9aqcLznyx3TqUQ8USZXnMVWxPOil5FQj/XJZnba+7Kfry2SH0mpclX8yLmYfHkHPsLxyIV9lxFSjo02iIuXuFsY0iJ0OIzlNMF9NZKsf7dgFJyTobiETpFUYb1d0xSi8kcSP2aM4p00Aw1eJPavczOMKhKdS+x+D6YKbVpTay9/14bmRyrxpoVsce9wsETN1jelkiuyHdKDbXGGPWndvfznxEvaRTu+aJEDG3yvgtVXGOY3l8fnoeraAc2ObpZ3uAA="

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- docker build -t alanbchristie/operator-pysimple -f build/Dockerfile .
- docker push alanbchristie/operator-pysimple
