---
language: minimal

services:
- docker

env:
  global:
  - secure: "W/DN2zK2rODKyKp68uU130BFQpYSxzrVHuGBF+IM+74lFnJieofAz98qZfdRivgSLly7FRCa8FiGHb3R3Qla0vC4iZvetAAeumLpOgxiSgXhZ/BLD2HTr3kmZwRN7smhsGchRwNEdyzW9Ww9diqiEN2G0FPcUGvjDbYshlf4KCyAJn1ezVGA2AaIuJfwJhRRuA6HclmLmPx4c5DAvHdQp/MUGPTu1Y1drXtbNYE0vNpeoDsK1OtU4ERCFjau7Dg0dakRN5FR44APoEUTWgndysCNjtr952YhmdCR06fI8fyWcqaoD1BvqmZ1N5Rz6klHDBgvNCGiZQ5yQK8w/zzBxeFk4/o6J68l8kQpMQ2TykBFq2z6pWy9HS7Yma9J1QmOGt0Na4sWxLybDIsda7LFRAkDZ+X7CbgTuY1A/dlh/LR5TisrowaU+uw+Kckej0kh8GNzO1N7OBZW63eeCASLZ39JUE3Lzhe9hGbVlyVavMPE6W6PZQnpnXOV5ULlCUpYUEPgxKAGtfq7awn87GX2Gat7/JtxNX9kVSyg7mOyfa3ebX23mcAiHl4LzItRtUEMTJGtxHkdX3KbRGAUy212syNxqRIiZ/ItxHir0drCjucYUu514YC132w3/9ZcuGUVdaSkkKxTVZajRouHRojGB4WmhsvCYz1tQ1OCmePcecA="
  - secure: "qyWUTObtBjwogj1p24el87AyjapDwNejH1hWVBrFzdrvx+zs1O+JYR9ygm3E/gKrH2uYUDR08zRGVn9oG/swxehHLJqRWwGn6xp20dywqp2BYDRkZQh5Z6Qxye6nlfV7ygVxJXGERgxXRwJoNSRuu7/ySB1SlzllopzcO5or73UMRa0D/oTB9CAN2vHgggiZIBx3n/O0vrOqW/gy0wdU8ErA9LtEApxtIsB37f3xSKOaieyMGnEeqStncusvsZyrIxWXc9s6gPJL9h72QvHWYF8H0ztABQkRGlUt3kYuHt0Je6DJR1n73GrYAKfZxsQzkLHq9dOiIbBdv5G36VNA9P3hYvCF1HqEmeI+61GA2Yotbu/dCwjYEqv1FrK0n16HlsCOpg9flQe42HRBKM/THcV9VnrL0byguzFh2kPkbJUr0c9L7fubeBCYV8fVNTirr4jQnhmhN1xU3xBn4EYkrAhX1XgZ8qGigXZ36bLhNndOgvczyjYZ+VI+mMAV92arOCmSUkUlkNYlwhAyXipUWLhHa3q8GEWQUpsRnPzWRaymiIXzXQ+NFGXqJBp4b+fw98A+ER0Try3jNn07rCz7O8BXPwRmkBwpx7n62T6sekootmz7nhJ4lNoe4m/ZyLJyaZh6Q5JRMB50Akmv7Jkh+f/gn0qvKhjQlLFUKTKqfqY="

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io

script:
- docker build -t alanbchristie/operator-pysimple -f build/Dockerfile .
- docker push alanbchristie/operator-pysimple
