---
language: python

services:
- docker

env:
  global:
  - secure: "RTEfnJCqxindIDPw+QFe2eqHdXhgFLzNa1RvKZPK9WxM0iOJWvQsbBXVisdheANCUi8w8nhVRsNiONO10N5qfjGpIxn1oJ48/dwyRWiRF0DenxJn86Ik3n+LfCkPL9VOpNJoJj3kuPvlYsdlBAkxv66qdwt2P0JFKArrHg/GT4ZI+JF/PVzoVS2zUP4RwUWQIc+Q0iG9X2G98owDw087hhUE3g6/fB68WMDFyg1h12jU/rzdpfP3cVqq+0yFi+mTZmVRHVR+ipELzwf4nOvyTHHDekpHJDRVfzpDZbxT9j14yXXcRCUrYzeJ1ehJWjFMXffexmjBhHRvXR2MdZusguIQKGIyQf2VbHAlUDjaBBj5Xowc2Lq1DCiw+mGldVcMeTXUxkNYu0NpIob7WWcQD4hAp5WgZn/8NiHH1TQqKwatuz3Rk6MBqWrMA9y8pSi2QCA6ckicNjgwXYLeFyYO6yOeOY50yd6EsSoQTL7mpGiJrvLGF3wooGgxyIttj2SSEcn2UMEjCqWQs5hsq1MriGj5uucNUiAQs85aQ/CoTEBqLcHFMXzm9e2Ne93SdoK6hsZ8gNGoVWUg4XHjBAJg9pXOGcXe+Ki6nQdaoprXoelOjaTOsnGtVKqTgkiyZ0Axof6Za2yLFo2JpGdg2oD3IJiMD/vLCD1WnBOa1e8Rx2Y="
  - secure: "Kun64Y/v8/rAxzazP0utlSN1ZP03VlLetymym+37rqP03FFg6ubql5k+6Zdfqz2rIUzrAsZPxJ01kwNdm/a6jHocuFjZgQwEszEBDXeOcvHUyM08WxyNavdmmQ4H7OTHtYxp19TcVjQeITveynNpD+agGDuEr4jUbwtbsNTMqMN1K3lVga6RLrGBA4gQ0BfNhXbOzAao16lK1Efm1qKVuT4B9bfrNdU8/uUhpHU1vdQ5rkzswUr6GXIi8qIcZ12PSoCQqeD4pD3G6Cyv/edsieGTFwYI9ATFyubrwcr/OwfRzlNVdLFXA4LEEKDyWP3nkQkyAMotK2v4tgXFnpEST4U2w6cYfakTz8dlW1HiVdmfBBMuDwBAQe/rv6NzMHy+yG0nfMIs/X/u8532pGm0rlZr68/0P4RRG8uhRlsm9eifuDWdIa5TLxdB/D3LAJgYtQRjC51knYbCbSXp44rFCnm9x+r43wCQRy3X3JqxKy31Z78KvmYGUliIfs3CrpaEkDCcKn95Bo3HnS3xJM1N45jFiFqhJRj4rF5jZgnbRaaiE8+y9+8MUL9GaIIAfdV+QJPWdgK6fYH66fvwjMaQ8QaKOc1/MorCDSorUZ43x+y9yrSSTuAPyEC/RZsw5+j1oit1VQStdUwAA75kzzI1rMLvatNFy9nE2V+iUus2u5c="

before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io

script:
- docker build -t alanbchristie/operator-pysimple -f build/Dockerfile .
- docker push alanbchristie/operator-pysimple
