---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pysimple-operator-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['unrestricted']

